spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${JDBC_PASSWORD:dev}
    url: jdbc:mysql://${JDBC_URL:localhost:3306}/${JDBC_DATABASE:docspace}
    username: ${JDBC_USER_NAME:dev}
  flyway:
    baselineOnMigrate: true
    enabled: true
    locations: classpath:migration/mysql
    password: ${JDBC_PASSWORD:dev}
    repeatable-sql-migration-prefix: R
    schemas: ${JDBC_DATABASE:docspace}
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    url: jdbc:mysql://${JDBC_URL:localhost:3306}/${JDBC_DATABASE:docspace}
    user: ${JDBC_USER_NAME:dev}
