spring:
  rabbitmq:
    addresses: ${RABBIT_URI:amqp://guest:guest@localhost/}
    host: ${RABBIT_HOST:localhost}
    listener:
      simple:
        retry:
          enabled: ${RABBIT_LISTENER_RETRY_ENABLED:true}
          initial-interval: ${RABBIT_LISTENER_RETRY_INITIAL_INTERVAL:1000}
          max-attempts: ${RABBIT_LISTENER_RETRY_MAX_ATTEMPTS:3}
          max-interval: ${RABBIT_LISTENER_RETRY_MAX_INTERVAL:3000}
          multiplier: ${RABBIT_LISTENER_RETRY_MULTIPLIER:3}
    password: ${RABBIT_PASSWORD:guest}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER_NAME:guest}
    virtual-host: ${RABBIT_VIRTUAL_HOST:}
    ssl:
      enabled: ${RABBIT_SSL_ENABLED:false}
      key-store: ${RABBIT_SSL_KEYSTORE:}
      key-store-password: ${RABBIT_SSL_KEYSTORE_PASSWORD:}
      trust-store: ${RABBIT_TRUST_STORE:}
      trust-store-password: ${RABBIT_TRUST_STORE_PASSWORD:}
  cloud:
    messaging:
      rabbitmq:
        queues:
          audit:
            deadExchange: ${RABBITMQ_AUDIT_DEAD_EXCHANGE:asc_identity_audit_dlx}
            deadQueue: ${RABBITMQ_AUDIT_DEAD_QUEUE:asc_identity_audit_dlq}
            deadRouting: ${RABBITMQ_AUDIT_DEAD_ROUTING:asc_identity_audit_dlr}
            exchange: ${RABBITMQ_AUDIT_EXCHANGE:asc_identity_audit_exchange}
            queue: ${RABBITMQ_AUDIT_QUEUE:asc_identity_audit_queue}
            routing: ${RABBITMQ_AUDIT_ROUTING:asc_identity_audit_routing}