spring:
  security:
    oauth2:
      registeredClient:
        accessTokenMinutesTTL: ${ACCESS_TOKEN_TTL:60}
        authorizationCodeMinutesTTL: ${AUTHORIZATION_CODE_TTL:1}
        refreshTokenDaysTTL: ${REFRESH_TOKEN_TTL:60}
