bucket4j:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DB:0}
    username: ${REDIS_USERNAME:}
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}
  rate-limits:
    limits:
      - method: GET
        capacity: ${GET_RATE_LIMITER_CAPACITY:200}
        refill:
          tokens: ${GET_RATE_LIMITER_REFILL:200}
          period: ${GET_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${GET_RATE_LIMITER_REFILL_UNIT:MINUTES}
      - method: POST
        capacity: ${POST_RATE_LIMITER_CAPACITY:10}
        refill:
          tokens: ${POST_RATE_LIMITER_REFILL:10}
          period: ${POST_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${POST_RATE_LIMITER_REFILL_UNIT:MINUTES}
      - method: PUT
        capacity: ${PUT_RATE_LIMITER_CAPACITY:15}
        refill:
          tokens: ${PUT_RATE_LIMITER_REFILL:15}
          period: ${PUT_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${PUT_RATE_LIMITER_REFILL_UNIT:MINUTES}
      - method: PATCH
        capacity: ${PATCH_RATE_LIMITER_CAPACITY:15}
        refill:
          tokens: ${PATCH_RATE_LIMITER_REFILL:15}
          period: ${PATCH_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${PATCH_RATE_LIMITER_REFILL_UNIT:MINUTES}
      - method: DELETE
        capacity: ${DELETE_RATE_LIMITER_CAPACITY:15}
        refill:
          tokens: ${DELETE_RATE_LIMITER_REFILL:15}
          period: ${DELETE_RATE_LIMITER_REFILL_PERIOD:1}
          time-unit: ${DELETE_RATE_LIMITER_REFILL_UNIT:MINUTES}

resilience4j:
  ratelimiter:
    instances:
      globalRateLimiter:
        eventConsumerBufferSize: ${RESILIENCE4J_RATELIMITER_GLOBAL_EVENT_BUFFER_SIZE:100}
        limitForPeriod: ${GLOBAL_RATE_LIMITER_CAPACITY:125}
        limitRefreshPeriod: ${GLOBAL_RATE_LIMITER_REFRESH_PERIOD:1s}
        timeoutDuration: ${GLOBAL_RATE_LIMITER_TIMEOUT_DURATION:0}
        registerHealthIndicator: ${GLOBAL_RATE_LIMITER_HEALTH_INDICATOR:true}
      publicRateLimiter:
        eventConsumerBufferSize: ${RESILIENCE4J_RATELIMITER_PUBLIC_EVENT_BUFFER_SIZE:50}
        limitForPeriod: ${PUBLIC_RATE_LIMITER_CAPACITY:25}
        limitRefreshPeriod: ${PUBLIC_RATE_LIMITER_REFRESH_PERIOD:1s}
        timeoutDuration: ${PUBLIC_RATE_LIMITER_TIMEOUT_DURATION:0}
        registerHealthIndicator: ${PUBLIC_RATE_LIMITER_HEALTH_INDICATOR:true}